<?php

namespace Database\Seeders;

use App\Models\User;

use Illuminate\Database\Seeder;

use Carbon\Carbon;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run()
    {
        // 1 Super Admin
        User::create([
            'firstname' => 'Super Admin',
            'middlename' => 'Super Admin',
            'lastname' => 'Super Admin',
            'suffix' => 'SA',
            'birthdate' => '2000-10-21',
            'birthplace' => 'Baguio City',
            'religion' => 'Catholic',
            'gender' => 'Male',
            'mothertongue' => 'English',
            'nationality' => 'Filipino',
            'pwdid' => 'ASDF1234',
            'height' => '168',
            'weight' => '70',
            'mobilenumber' => '09176820721',
            'email' => 'sadmin@sadmin.com',
            'address' => 'Guisad Central, Baguio City',
            'school_kinder' => 'SLU-LES',
            'school_kindergrad' => '2007',
            'school_elementary' => 'Calvary Baptist Elementary School',
            'school_elementarygrad' => '2010',
            'school_juniorhigh' => 'University of Baguio',
            'lrn' => 'QWER1234',
            'esc' => 'ZXCV1234',
            'qvr' => 'HJKL1234',
            'public_id' => 'UIOP1234',
            'beneficiary' => 'Juan Dela Cruz',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09176820722',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'mparent_name' => 'Jane Doe',
            'mparent_number' => '09176820723',
            'mparent_occupation' => 'Teacher',
            'mparent_address' => 'General Luna',
            'fparent_name' => 'Jonathan Doe',
            'fparent_number' => '09176820724',
            'fparent_occupation' => 'Police',
            'fparent_address' => 'General Luna',
            'pag_ibig' => 'FSAD4235',
            'philhealth' => 'FADS4251',
            'sss' => 'DAFS2534',
            'tin' => 'SADF5234',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('sadmin123'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Super Admin');

        // 1 Admin | Staff
        User::create([
            'firstname' => 'Alexander',
            'middlename' => 'Churro',
            'lastname' => 'Am-uno',
            'suffix' => 'Jr.',
            'birthdate' => '2013-08-01',
            'birthplace' => 'Baguio City',
            'religion' => 'Catholic',
            'gender' => 'Male',
            'mothertongue' => 'English',
            'nationality' => 'Filipino',
            'height' => '124',
            'weight' => '43',
            'mobilenumber' => '09158390231',
            'email' => 'alexanderamuno@s.caims.com',
            'address' => 'Guisad Central, Baguio City',
            'beneficiary' => 'Juan Dela Cruz',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09176820766',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'pag_ibig' => 'FSAD4239',
            'philhealth' => 'FADS4281',
            'sss' => 'DAFS2034',
            'tin' => 'SADF1434',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('staff123'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Admin');

        // 2 Accountants

        // Accountant 1
        User::create([
            'firstname' => 'Leonardo',
            'middlename' => 'Haroon',
            'lastname' => 'Jamie',
            'birthdate' => '1995-12-01',
            'birthplace' => 'Baguio City',
            'religion' => 'Catholic',
            'gender' => 'Male',
            'mothertongue' => 'English',
            'nationality' => 'Filipino',
            'height' => '170',
            'weight' => '70',
            'mobilenumber' => '09164739198',
            'email' => 'leonardJamie@a.caims.com',
            'address' => 'Guisad Central, Baguio City',
            'beneficiary' => 'Juan Dela Cruz',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09176820733',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'pag_ibig' => 'FSDD4331',
            'philhealth' => 'FADS4431',
            'sss' => 'DAFS2154',
            'tin' => 'SADF1264',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('finance1'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Accountant');

        // Accountant 2
        User::create([
            'firstname' => 'Mary',
            'middlename' => 'Grace',
            'lastname' => 'Dela Cruz',
            'birthdate' => '1993-10-21',
            'birthplace' => 'Baguio City',
            'religion' => 'Anglican',
            'gender' => 'Female',
            'mothertongue' => 'Tagalog',
            'nationality' => 'Filipino',
            'height' => '143',
            'weight' => '56',
            'mobilenumber' => '09178492301',
            'email' => 'marygrace@a.caims.com',
            'address' => 'Trancoville, Baguio City',
            'emergency_contact_name' => 'Carding Dalisay',
            'emergency_contact_number' => '09152735932',
            'emergency_contact_occupation' => 'Teacher',
            'emergency_contact_address' => 'Bakakeng',
            'emergency_contact_relationship' => 'Uncle',
            'pag_ibig' => 'UIOP4213',
            'philhealth' => 'FSDA5231',
            'sss' => 'HJKL4213',
            'tin' => 'QWER0593',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('finance2'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Accountant');

        // 3 Teachers

        // Teacher 1
        User::create([
            'firstname' => 'Julie',
            'middlename' => 'Bondad',
            'lastname' => 'Abalos',
            'birthdate' => '1998-11-01',
            'birthplace' => 'Baguio City',
            'religion' => 'Catholic',
            'gender' => 'Female',
            'mothertongue' => 'Ilokano',
            'nationality' => 'Filipino',
            'height' => '150',
            'weight' => '58',
            'mobilenumber' => '09165438293',
            'email' => 'julsabalos@t.caims.com',
            'address' => 'Guisad Central, Baguio City',
            'beneficiary' => 'Juan Dela Cruz',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09176820744',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'pag_ibig' => '4231FSAD',
            'philhealth' => 'FADS4221',
            'sss' => 'DAFS3134',
            'tin' => 'SADF1534',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('teacher1'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Teacher');

        // Teacher 2
        User::create([
            'firstname' => 'Russel',
            'middlename' => 'Liclic',
            'lastname' => 'Fernandez',
            'birthdate' => '1990-05-14',
            'birthplace' => 'Baguio City',
            'religion' => 'Catholic',
            'gender' => 'Male',
            'mothertongue' => 'English',
            'nationality' => 'Filipino',
            'height' => '175',
            'weight' => '76',
            'mobilenumber' => '09215438295',
            'email' => 'russfernandez@t.caims.com',
            'address' => 'Leonila Hill, Baguio City',
            'beneficiary' => 'John Dela Torre',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09216821021',
            'emergency_contact_occupation' => 'Teacher',
            'emergency_contact_address' => 'Crystal Cave',
            'emergency_contact_relationship' => 'Brother',
            'pag_ibig' => 'FSAD4643',
            'philhealth' => 'TYUI6894',
            'sss' => 'BNMA1453',
            'tin' => 'TYRU4213',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('teacher2'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Teacher');

        // Teacher 3
        User::create([
            'firstname' => 'Heidi',
            'middlename' => 'Jukutan',
            'lastname' => 'Tabanda',
            'suffix' => 'Ms.',
            'birthdate' => '1997-07-02',
            'birthplace' => 'Baguio City',
            'religion' => 'Iglesia ni Cristo',
            'gender' => 'Female',
            'mothertongue' => 'English',
            'nationality' => 'Filipino',
            'height' => '155',
            'weight' => '63',
            'mobilenumber' => '09165438295',
            'email' => 'heiditabanda@t.caims.com',
            'address' => 'Badihoy, Baguio City',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09166825342',
            'emergency_contact_occupation' => 'Police',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Father',
            'pag_ibig' => 'FSAD0031',
            'philhealth' => 'FADS4200',
            'sss' => 'DASF1134',
            'tin' => 'FSAD6784',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('teacher3'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Teacher');

        // 20 Students

        // Student 1
        User::create([
            'firstname' => 'Cayden',
            'middlename' => 'Zackary',
            'lastname' => 'Jackson',
            'suffix' => 'SA',
            'birthdate' => '2012-01-12',
            'birthplace' => 'Baguio City',
            'religion' => 'Iglesia ni Cristo',
            'gender' => 'Male',
            'mothertongue' => 'English',
            'nationality' => 'Filipino',
            'height' => '165',
            'weight' => '57.2',
            'mobilenumber' => '09274294577',
            'email' => 'jacksoncayden@s.caims.edu',
            'address' => 'Pablo Ocampo Sr. Ext, Baguio City',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09176820767',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('student1'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Student');

        // Student 2
        User::create([
            'firstname' => 'Frederick',
            'middlename' => 'Miguel',
            'lastname' => 'Balon',
            'suffix' => 'SA',
            'birthdate' => '2011-06-20',
            'birthplace' => 'Sarrat, Ilocos Norte',
            'religion' => 'None',
            'gender' => 'Male',
            'mothertongue' => 'Ilokano',
            'nationality' => 'Filipino',
            'height' => '143.5',
            'weight' => '41.6',
            'mobilenumber' => '09983315305',
            'email' => 'balonfrederick@s.caims.edu',
            'address' => 'San Agustin, Baguio City',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09176820768',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('student2'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Student');

        // Student 3
        User::create([
            'firstname' => 'Jacqueline',
            'middlename' => 'Audrina',
            'lastname' => 'Reyes',
            'suffix' => 'SA',
            'birthdate' => '2006-09-13',
            'birthplace' => 'Baguio City',
            'religion' => 'Catholic',
            'gender' => 'Female',
            'mothertongue' => 'Ilokano',
            'nationality' => 'Filipino',
            'height' => '162.5',
            'weight' => '63.9',
            'mobilenumber' => '09664861698',
            'email' => 'reyesjacqueline@s.caims.edu',
            'address' => 'Ben Harrison, Baguio City',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09176820769',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('student3'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Student');

        // Student 4
        User::create([
            'firstname' => 'Jose',
            'middlename' => 'Go',
            'lastname' => 'Chan',
            'suffix' => 'SA',
            'birthdate' => '2004-10-02',
            'birthplace' => 'Baguio City',
            'religion' => 'Catholic',
            'gender' => 'Male',
            'mothertongue' => 'English',
            'nationality' => 'Filipino',
            'height' => '170.2',
            'weight' => '70.4',
            'mobilenumber' => '09224661698',
            'email' => 'chanjose@s.caims.edu',
            'address' => 'Legarda, Baguio City',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09176885662',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('student4'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Student');

        // Student 5
        User::create([
            'firstname' => 'Stacey',
            'middlename' => 'Balicha',
            'lastname' => 'Bautista',
            'suffix' => 'SA',
            'birthdate' => '2005-04-04',
            'birthplace' => 'Baguio City',
            'religion' => 'Catholic',
            'gender' => 'Female',
            'mothertongue' => 'English',
            'nationality' => 'Filipino',
            'height' => '156.8',
            'weight' => '65.2',
            'mobilenumber' => '09334861423',
            'email' => 'bautistastacey@s.caims.edu',
            'address' => 'Crystal Cave, Baguio City',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09176853251',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('student5'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Student');

        // Student 6
        User::create([
            'firstname' => 'Beatrice',
            'middlename' => 'Tan',
            'lastname' => 'Choy',
            'suffix' => 'SA',
            'birthdate' => '2007-11-11',
            'birthplace' => 'Baguio City',
            'religion' => 'Catholic',
            'gender' => 'Female',
            'mothertongue' => 'English',
            'nationality' => 'Filipino',
            'height' => '165',
            'weight' => '65',
            'mobilenumber' => '09174861699',
            'email' => 'choybeatrice@s.caims.edu',
            'address' => 'Easter Hills, Baguio City',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09216820760',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('student6'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Student');

        // Student 7
        User::create([
            'firstname' => 'Ivan',
            'middlename' => 'Carpio',
            'lastname' => 'Aquino',
            'suffix' => 'SA',
            'birthdate' => '2006-01-04',
            'birthplace' => 'Baguio City',
            'religion' => 'None',
            'gender' => 'Male',
            'mothertongue' => 'Ilokano',
            'nationality' => 'Filipino',
            'height' => '166.5',
            'weight' => '76.3',
            'mobilenumber' => '09124861694',
            'email' => 'aquinoivan@s.caims.edu',
            'address' => 'San Luis, Baguio City',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09246820532',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('student7'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Student');

        // Student 8
        User::create([
            'firstname' => 'Eric',
            'middlename' => 'Bondad',
            'lastname' => 'Labos',
            'suffix' => 'SA',
            'birthdate' => '2005-12-25',
            'birthplace' => 'Baguio City',
            'religion' => 'Anglican',
            'gender' => 'Male',
            'mothertongue' => 'English',
            'nationality' => 'Filipino',
            'height' => '164.3',
            'weight' => '62.4',
            'mobilenumber' => '09334861532',
            'email' => 'laboseric@s.caims.edu',
            'address' => 'Brookside, Baguio City',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09666820436',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('student8'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Student');

        // Student 9
        User::create([
            'firstname' => 'Charles',
            'middlename' => 'Lim',
            'lastname' => 'Choi',
            'suffix' => 'SA',
            'birthdate' => '2003-11-13',
            'birthplace' => 'Baguio City',
            'religion' => 'Catholic',
            'gender' => 'Male',
            'mothertongue' => 'English',
            'nationality' => 'Filipino',
            'height' => '169.4',
            'weight' => '72.6',
            'mobilenumber' => '09094861321',
            'email' => 'choicharles@s.caims.edu',
            'address' => 'Malvar, Baguio City',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09776820654',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('student9'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Student');

        // Student 10
        User::create([
            'firstname' => 'Jin',
            'middlename' => 'Daewo',
            'lastname' => 'Mori',
            'suffix' => 'SA',
            'birthdate' => '2012-10-21',
            'birthplace' => 'Seoul',
            'religion' => 'None',
            'gender' => 'Male',
            'mothertongue' => 'Hangugeo',
            'nationality' => 'Korean',
            'height' => '147.2',
            'weight' => '43.4',
            'mobilenumber' => '09334864215',
            'email' => 'morijin@s.caims.edu',
            'address' => 'Goshen Land, Baguio City',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09776820420',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('student10'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Student');

        // Student 11
        User::create([
            'firstname' => 'Inori',
            'middlename' => 'Bijin',
            'lastname' => 'Minase',
            'suffix' => 'SA',
            'birthdate' => '2010-11-21',
            'birthplace' => 'Tokyo',
            'religion' => 'None',
            'gender' => 'Female',
            'mothertongue' => 'Hiragana',
            'nationality' => 'Japanese',
            'height' => '154.4',
            'weight' => '54.5',
            'mobilenumber' => '09224423215',
            'email' => 'minaseinori@s.caims.edu',
            'address' => 'Megatower Residences, Baguio City',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09226820690',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('student11'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Student');

        // Student 12
        User::create([
            'firstname' => 'Kyla',
            'middlename' => 'Garcia',
            'lastname' => 'Lao',
            'suffix' => 'SA',
            'birthdate' => '2007-04-03',
            'birthplace' => 'La Union',
            'religion' => 'Catholic',
            'gender' => 'Female',
            'mothertongue' => 'Tagalog',
            'nationality' => 'Filipino',
            'height' => '157.8',
            'weight' => '77.5',
            'mobilenumber' => '09125331215',
            'email' => 'laokyla@s.caims.edu',
            'address' => 'Loakan, Baguio City',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09758392300',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('student12'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Student');

        // Student 13
        User::create([
            'firstname' => 'Philip',
            'middlename' => 'Algones',
            'lastname' => 'Sy',
            'suffix' => 'SA',
            'birthdate' => '2004-05-15',
            'birthplace' => 'Baguio City',
            'religion' => 'Catholic',
            'gender' => 'Male',
            'mothertongue' => 'English',
            'nationality' => 'Filipino',
            'height' => '173',
            'weight' => '72.4',
            'mobilenumber' => '09234864530',
            'email' => 'syphilip@s.caims.edu',
            'address' => 'Camp 7, Baguio City',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09770000420',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('student13'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Student');

        // Student 14
        User::create([
            'firstname' => 'Derek',
            'middlename' => 'Arboleda',
            'lastname' => 'Sanchez',
            'suffix' => 'SA',
            'birthdate' => '2006-04-26',
            'birthplace' => 'Pangasinan',
            'religion' => 'Catholic',
            'gender' => 'Male',
            'mothertongue' => 'Tagalog',
            'nationality' => 'Filipino',
            'height' => '164',
            'weight' => '78.3',
            'mobilenumber' => '09114324234',
            'email' => 'sanchezderek@s.caims.edu',
            'address' => 'Quezon Hill, Baguio City',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09996869420',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('student14'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Student');

        // Student 15
        User::create([
            'firstname' => 'Jenevy',
            'middlename' => 'Rabina',
            'lastname' => 'Paran',
            'suffix' => 'SA',
            'birthdate' => '2012-08-09',
            'birthplace' => 'Cagayan',
            'religion' => 'Catholic',
            'gender' => 'Female',
            'mothertongue' => 'Tagalog',
            'nationality' => 'Filipino',
            'height' => '147.3',
            'weight' => '54.3',
            'mobilenumber' => '09116544790',
            'email' => 'paranjenevy@s.caims.edu',
            'address' => 'Camdas, Baguio City',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09090894231',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('student15'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Student');

        // Student 16
        User::create([
            'firstname' => 'Aaron',
            'middlename' => 'Co',
            'lastname' => 'Aoyong',
            'suffix' => 'SA',
            'birthdate' => '2006-02-28',
            'birthplace' => 'Baguio City',
            'religion' => 'None',
            'gender' => 'Male',
            'mothertongue' => 'English',
            'nationality' => 'Filipino',
            'height' => '181.3',
            'weight' => '75.7',
            'mobilenumber' => '09224866520',
            'email' => 'aoyongaaron@s.caims.edu',
            'address' => 'Legarda, Baguio City',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09336827565',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('student16'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Student');

        // Student 17
        User::create([
            'firstname' => 'Cedrix',
            'middlename' => 'Lourdes',
            'lastname' => 'Orendain',
            'suffix' => 'SA',
            'birthdate' => '2008-06-01',
            'birthplace' => 'Baguio City',
            'religion' => 'Iglesia ni Cristo',
            'gender' => 'Male',
            'mothertongue' => 'Tagalog',
            'nationality' => 'Filipino',
            'height' => '160.2',
            'weight' => '63.6',
            'mobilenumber' => '09444862213',
            'email' => 'orendaincedrix@s.caims.edu',
            'address' => 'San Carlos, Baguio City',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09110903421',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('student17'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Student');

        // Student 18
        User::create([
            'firstname' => 'Dahren',
            'middlename' => 'Bautista',
            'lastname' => 'Aquino',
            'suffix' => 'SA',
            'birthdate' => '2004-10-30',
            'birthplace' => 'Baguio City',
            'religion' => 'None',
            'gender' => 'Male',
            'mothertongue' => 'English',
            'nationality' => 'Filipino',
            'height' => '168.4',
            'weight' => '70.4',
            'mobilenumber' => '09554863421',
            'email' => 'aquinodahren@s.caims.edu',
            'address' => 'Suello, Baguio City',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09770900908',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('student17'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Student');

        // Student 19
        User::create([
            'firstname' => 'Joni',
            'middlename' => 'Algones',
            'lastname' => 'Aglipay',
            'suffix' => 'SA',
            'birthdate' => '2006-07-23',
            'birthplace' => 'Baguio City',
            'religion' => 'Jehovah',
            'gender' => 'Female',
            'mothertongue' => 'English',
            'nationality' => 'Filipino',
            'height' => '154.4',
            'weight' => '68.2',
            'mobilenumber' => '09333862009',
            'email' => 'aglipayjoni@s.caims.edu',
            'address' => 'Tip Top, Baguio City',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09656906472',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('student17'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Student');

        // Student 20
        User::create([
            'firstname' => 'Johnrev',
            'middlename' => 'Sayan',
            'lastname' => 'Gat-eb',
            'suffix' => 'SA',
            'birthdate' => '2007-04-26',
            'birthplace' => 'Baguio City',
            'religion' => 'Born Again',
            'gender' => 'Male',
            'mothertongue' => 'Tagalog',
            'nationality' => 'Filipino',
            'height' => '164.3',
            'weight' => '80.4',
            'mobilenumber' => '09333235321',
            'email' => 'gatebjohnrev@s.caims.edu',
            'address' => 'Fairview, Baguio City',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09657801423',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('student17'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Student');
    }
}
