<?php

namespace Database\Seeders;

use App\Models\User;

use Illuminate\Database\Seeder;

use Carbon\Carbon;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run()
    {
        User::create([
            'firstname' => 'Super Admin',
            'middlename' => 'Super Admin',
            'lastname' => 'Super Admin',
            'suffix' => 'SA',
            'birthdate' => '2000-10-21',
            'birthplace' => 'Baguio City',
            'religion' => 'Catholic',
            'gender' => 'Male',
            'mothertongue' => 'English',
            'nationality' => 'Filipino',
            'pwdid' => 'ASDF1234',
            'height' => '168',
            'weight' => '70',
            'mobilenumber' => '09176820721',
            'email' => 'sadmin@sadmin.com',
            'address' => 'Guisad Central, Baguio City',
            'school_kinder' => 'SLU-LES',
            'school_kindergrad' => '2007',
            'school_elementary' => 'Calvary Baptist Elementary School',
            'school_elementarygrad' => '2010',
            'school_juniorhigh' => 'University of Baguio',
            'lrn' => 'QWER1234',
            'esc' => 'ZXCV1234',
            'qvr' => 'HJKL1234',
            'public_id' => 'UIOP1234',
            'beneficiary' => 'Juan Dela Cruz',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09176820722',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'mparent_name' => 'Jane Doe',
            'mparent_number' => '09176820723',
            'mparent_occupation' => 'Teacher',
            'mparent_address' => 'General Luna',
            'fparent_name' => 'Jonathan Doe',
            'fparent_number' => '09176820724',
            'fparent_occupation' => 'Police',
            'fparent_address' => 'General Luna',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('sadmin123'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Super Admin');

        User::create([
            'firstname' => 'Leonardo',
            'middlename' => 'Haroon',
            'lastname' => 'Jamie',
            'suffix' => 'SA',
            'birthdate' => '1995-12-01',
            'birthplace' => 'Baguio City',
            'religion' => 'Catholic',
            'gender' => 'Male',
            'mothertongue' => 'English',
            'nationality' => 'Filipino',
            'height' => '170',
            'weight' => '70',
            'mobilenumber' => '09164739198',
            'email' => 'leonardJamie@a.caims.com',
            'address' => 'Guisad Central, Baguio City',

            'beneficiary' => 'Juan Dela Cruz',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09176820733',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('finance'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Accountant');

        User::create([
            'firstname' => 'Julie',
            'middlename' => 'Ambakols',
            'lastname' => 'Killi',
            'suffix' => 'Ms.',
            'birthdate' => '1998-11-01',
            'birthplace' => 'Baguio City',
            'religion' => 'Catholic',
            'gender' => 'Female',
            'mothertongue' => 'English',
            'nationality' => 'Filipino',
            'height' => '150',
            'weight' => '58',
            'mobilenumber' => '09165438293',
            'email' => 'julsKilli@t.caims.com',
            'address' => 'Guisad Central, Baguio City',
            'beneficiary' => 'Juan Dela Cruz',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09176820744',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('teacher'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Teacher');

        User::create([
            'firstname' => 'Juliett',
            'middlename' => 'Ambaken',
            'lastname' => 'Killiy',
            'suffix' => 'Ms.',
            'birthdate' => '1996-11-11',
            'birthplace' => 'Baguio City',
            'religion' => 'Catholic',
            'gender' => 'Female',
            'mothertongue' => 'English',
            'nationality' => 'Filipino',
            'height' => '155',
            'weight' => '63',
            'mobilenumber' => '09165438295',
            'email' => 'juliettKilliy@t.caims.com',
            'address' => 'Guisad Central, Baguio City',
            'beneficiary' => 'Juan Dela Cruz',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09176820755',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('teacher123'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Teacher');


        User::create([
            'firstname' => 'Alexander',
            'middlename' => 'Churro',
            'lastname' => 'Am-uno',
            'suffix' => 'Mr.',
            'birthdate' => '2013-08-01',
            'birthplace' => 'Baguio City',
            'religion' => 'Catholic',
            'gender' => 'Male',
            'mothertongue' => 'English',
            'nationality' => 'Filipino',
            'height' => '124',
            'weight' => '43',
            'mobilenumber' => '09158390231',
            'email' => 'alexanderamuno@s.caims.com',
            'address' => 'Guisad Central, Baguio City',
            'beneficiary' => 'Juan Dela Cruz',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09176820766',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('student'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Admin');

        User::create([
            'firstname' => 'Cayden',
            'middlename' => 'Zackary',
            'lastname' => 'Jackson',
            'suffix' => 'SA',
            'birthdate' => '2012-01-12',
            'birthplace' => 'Baguio City',
            'religion' => 'Iglesia ni Cristo',
            'gender' => 'Male',
            'mothertongue' => 'English',
            'nationality' => 'Filipino',
            'height' => '165',
            'weight' => '57.2',
            'mobilenumber' => '09274294577',
            'email' => 'jacksoncayden@s.caims.edu',
            'address' => 'Pablo Ocampo Sr. Ext, Baguio City',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09176820767',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('student1'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Student');

        User::create([
            'firstname' => 'Frederick',
            'middlename' => 'Miguel',
            'lastname' => 'Balon',
            'suffix' => 'SA',
            'birthdate' => '2011-06-20',
            'birthplace' => 'Sarrat, Ilocos Norte',
            'religion' => 'None',
            'gender' => 'Male',
            'mothertongue' => 'Ilokano',
            'nationality' => 'Filipino',
            'height' => '143.5',
            'weight' => '41.6',
            'mobilenumber' => '09983315305',
            'email' => 'balonfrederick@s.caims.edu',
            'address' => 'San Agustin, Baguio City',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09176820768',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('student2'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Student');

        User::create([
            'firstname' => 'Jacqueline',
            'middlename' => 'Audrina',
            'lastname' => 'Reyes',
            'suffix' => 'SA',
            'birthdate' => '2006-09-13',
            'birthplace' => 'Baguio City',
            'religion' => 'Catholic',
            'gender' => 'Female',
            'mothertongue' => 'Ilokano',
            'nationality' => 'Filipino',
            'height' => '162.5',
            'weight' => '63.9',
            'mobilenumber' => '09664861698',
            'email' => 'reyesjacqueline@s.caims.edu',
            'address' => 'Ben Harrison, Baguio City',
            'emergency_contact_name' => 'John Doe',
            'emergency_contact_number' => '09176820769',
            'emergency_contact_occupation' => 'Pastor',
            'emergency_contact_address' => 'Trancoville',
            'emergency_contact_relationship' => 'Uncle',
            'email_verified_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => Hash::make('student3'),
            'remember_token' => NULL,
            'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
        ])->assignRole('Student');
    }
}
